// setup_management_processor — Capability for setup and configuration management.
// Implements ISetupManagementProtocol: generate_env, generate_mcp_config.

use std::collections::HashMap;

/// Generated .env file content.
pub struct EnvContent {
    pub value: String,
}

/// Generic JSON-like configuration value object.
pub struct McpConfig {
    pub value: HashMap<String, serde_json::Value>,
}

/// Business logic for generating setup and configuration artifacts.
pub struct SetupManagementProcessor;

impl SetupManagementProcessor {
    pub fn new() -> Self {
        Self
    }

    /// Generate .env content for the auto-linter environment.
    pub fn generate_env(&self, home_dir: &str) -> EnvContent {
        let lines = vec![
            "# Auto-Linter Environment Configuration".to_string(),
            "# Generated by: auto-linter init".to_string(),
            "".to_string(),
            "# Phantom root (for JS/TS linters):".to_string(),
            format!("PHANTOM_ROOT={}/", home_dir),
        ];
        EnvContent { value: lines.join("\n") + "\n" }
    }

    /// Generate the base mcp.json entry for auto-linter.
    pub fn generate_mcp_config(&self) -> McpConfig {
        let mut config = HashMap::new();
        let server_entry = serde_json::json!({
            "command": "auto-linter",
            "args": [],
            "alwaysAllow": ["lint", "execute_command", "health_check", "list_commands", "read_skill_context"]
        });
        config.insert("auto-linter".to_string(), server_entry);
        McpConfig { value: config }
    }

    /// Generate Claude Desktop MCP config format.
    pub fn mcp_config_claude(&self) -> McpConfig {
        let base = self.generate_mcp_config();
        let mut config = HashMap::new();
        config.insert(
            "mcpServers".to_string(),
            serde_json::json!(base.value),
        );
        McpConfig { value: config }
    }

    /// Generate Hermes/Antigravity MCP config format.
    pub fn mcp_config_hermes(&self) -> McpConfig {
        self.generate_mcp_config()
    }

    /// Generate VS Code MCP config format.
    pub fn mcp_config_vscode(&self) -> McpConfig {
        let base = self.generate_mcp_config();
        let mut config = HashMap::new();
        config.insert(
            "mcp".to_string(),
            serde_json::json!({"servers": base.value}),
        );
        McpConfig { value: config }
    }
}
