#!/bin/bash
#
# Blender MCP CLI Installer
# Installs blender-cli and blender-mcp globally in ~/.local/bin via editable venv.
#
# Run: bash scripts/install_cli.sh
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
VENV_DIR="${PROJECT_ROOT}/.env" # Check default .env directory

# Detect virtual environment folder (.venv or .env)
if [ -d "${PROJECT_ROOT}/.venv" ]; then
  VENV_DIR="${PROJECT_ROOT}/.venv"
elif [ -d "${PROJECT_ROOT}/.env" ]; then
  VENV_DIR="${PROJECT_ROOT}/.env"
else
  echo "[!] Creating virtual environment..."
  python3 -m venv "${PROJECT_ROOT}/.venv"
  VENV_DIR="${PROJECT_ROOT}/.venv"
fi

echo "=== Blender MCP CLI Installer ==="
echo "Project Root: ${PROJECT_ROOT}"
echo "Virtual Env:  ${VENV_DIR}"
echo ""

# 1. Install package in editable mode
echo "[*] Installing blender-mcp in editable mode..."
if [ -f "${PROJECT_ROOT}/uv.lock" ] && command -v uv &> /dev/null; then
  echo "    Using uv for lightning fast installation..."
  (cd "${PROJECT_ROOT}" && uv pip install -e .)
else
  "${VENV_DIR}/bin/pip" install -e "${PROJECT_ROOT}"
fi

echo "✓ Package installed successfully inside virtual environment."
echo ""

# 2. Expose executables in ~/.local/bin
LOCAL_BIN="${HOME}/.local/bin"
mkdir -p "${LOCAL_BIN}"

create_wrapper() {
  local cmd_name="$1"
  local target_executable="${VENV_DIR}/bin/${cmd_name}"
  local wrapper_path="${LOCAL_BIN}/${cmd_name}"

  echo "[*] Creating global wrapper for ${cmd_name} in ${wrapper_path}..."
  cat << EOF > "${wrapper_path}"
#!/bin/bash
# Wrapper generated by install_cli.sh
exec "${target_executable}" "\$@"
EOF
  chmod +x "${wrapper_path}"
}

create_wrapper "blender-cli"
create_wrapper "blender-mcp"

echo ""
echo "=== Installation Complete ==="
echo "You can now run the commands directly:"
echo "  blender-cli --help"
echo "  blender-mcp --help"
echo ""
if [[ ":$PATH:" != *":${LOCAL_BIN}:"* ]]; then
  echo "[!] WARNING: ${LOCAL_BIN} is not in your PATH."
  echo "    Please add this line to your ~/.bashrc or ~/.zshrc:"
  echo "    export PATH=\"\$HOME/.local/bin:\$PATH\""
fi

