"""Capability for setup and configuration management."""

from ..taxonomy import (
    DirectoryPath,
    EnvContentVO,
    McpConfigVO,
    MetadataVO,
)
from ..contract import ISetupManagementProtocol


class SetupManagementProcessor(ISetupManagementProtocol):
    """Assistant Chef for setup and configuration."""

    def __init__(self, http_provider=None):
        self.http_provider = http_provider

    def generate_env(self, home: DirectoryPath) -> EnvContentVO:
        """Generate .env content (Logic/Recipe)."""
        home_val = str(home.value)

        lines = [
            "# Auto-Linter Environment Configuration",
            "# Generated by: auto-linter init",
            "",
            "# Phantom root (for JS/TS linters):",
            f"PHANTOM_ROOT={home_val}/",
        ]
        return EnvContentVO(value="\n".join(lines) + "\n")

    def generate_mcp_config(self) -> McpConfigVO:
        """Generate mcp.json entry (Logic/Recipe)."""
        config = {
            "auto-linter": {
                "command": "auto-linter",
                "args": [],
                "alwaysAllow": [
                    "lint",
                    "execute_command",
                    "health_check",
                    "list_commands",
                    "read_skill_context",
                ],
            }
        }
        return McpConfigVO(value=MetadataVO(value=config))

    def mcp_config_claude(self) -> McpConfigVO:
        """Claude Desktop MCP config."""
        config = {"mcpServers": self.generate_mcp_config().value.value}
        return McpConfigVO(value=MetadataVO(value=config))

    def mcp_config_hermes(self) -> McpConfigVO:
        """Hermes MCP config."""
        config_vo = self.generate_mcp_config()
        return config_vo

    def mcp_config_vscode(self) -> McpConfigVO:
        """VS Code MCP config."""
        config = {"mcp": {"servers": self.generate_mcp_config().value.value}}
        return McpConfigVO(value=MetadataVO(value=config))
