"""Tencent Hunyuan3D AI 3D generation tools"""

import json
import logging
from typing import Any

from contract import BlenderConnectionPort, HunyuanToolPort
from taxonomy import ActionName, JobId, JobState, ObjectName, Prompt, ResultUrl, StatusString

logger = logging.getLogger("BlenderMCPServer")


class HunyuanGenerationTool(HunyuanToolPort):
    """Tool implementation for Tencent Hunyuan3D AI 3D Generation."""

    _job_id_ref: JobId = JobId("hunyuan-ref")
    _job_state_ref: JobState = JobState("pending")

    def __init__(self, connection: BlenderConnectionPort):
        """Initialize with an explicit connection port."""
        self._connection = connection

    @property
    def connection(self) -> BlenderConnectionPort:
        return self._connection

    def get_hunyuan3d_status(self) -> StatusString:
        """
        Check if Hunyuan3D integration is enabled in Blender.
        Returns a message indicating whether Hunyuan3D features are available.
        """
        try:
            blender = self.connection
            result = blender.send_command(ActionName("get_hunyuan3d_status"))
            message = str(result.get("message", ""))
            return StatusString(message)
        except Exception as e:
            logger.error(f"Error checking Hunyuan3D status: {str(e)}")
            return StatusString(f"Error checking Hunyuan3D status: {str(e)}")

    def generate_hunyuan3d_model(
        self, text_prompt: Prompt | None = None, input_image_url: ResultUrl | None = None
    ) -> StatusString:
        """
        Generate 3D asset using Hunyuan3D by providing either text description, image reference,
        or both for the desired asset, and import the asset into Blender.
        """
        try:
            blender = self.connection
            result = blender.send_command(
                ActionName("create_hunyuan_job"),
                {
                    "text_prompt": text_prompt,
                    "image": input_image_url,
                },
            )
            if "Response" in result and "JobId" in result.get("Response", {}):
                job_id = result["Response"]["JobId"]
                formatted_job_id = f"job_{job_id}"
                return StatusString(
                    json.dumps(
                        {
                            "job_id": formatted_job_id,
                        }
                    )
                )
            return StatusString(json.dumps(result))
        except Exception as e:
            logger.error(f"Error generating Hunyuan3D task: {str(e)}")
            return StatusString(f"Error generating Hunyuan3D task: {str(e)}")

    def poll_hunyuan_job_status(
        self,
        job_id: JobId | None = None,
    ) -> StatusString:
        """
        Check if the Hunyuan3D generation task is completed.
        """
        try:
            blender = self.connection
            kwargs = {
                "job_id": job_id,
            }
            result = blender.send_command(ActionName("poll_hunyuan_job_status"), kwargs)
            return StatusString(json.dumps(result))
        except Exception as e:
            logger.error(f"Error polling Hunyuan3D status: {str(e)}")
            return StatusString(f"Error polling Hunyuan3D status: {str(e)}")

    def import_generated_asset_hunyuan(
        self,
        name: ObjectName,
        zip_file_url: ResultUrl,
    ) -> StatusString:
        """
        Import the asset generated by Hunyuan3D after the generation task is completed.
        """
        try:
            blender = self.connection
            kwargs: dict[str, Any] = {"name": name}
            if zip_file_url:
                kwargs["zip_file_url"] = zip_file_url
                result = blender.send_command(ActionName("import_generated_asset_hunyuan"), kwargs)
                return StatusString(json.dumps(result))
            raise ValueError("zip_file_url is required")
        except Exception as e:
            logger.error(f"Error importing Hunyuan3D asset: {str(e)}")
            return StatusString(f"Error importing Hunyuan3D asset: {str(e)}")
