' Automatically generated by DesktopCommanderMCP Windows Service Installer
Set WshShell = CreateObject("WScript.Shell")
WshShell.Run """C:\Program Files\nodejs\node.exe"" ""C:\Users\Administrator\mcp-servers\DesktopCommanderMCP\dist\index.js"" --port 8080", 0, false