"""Taxonomy barrel: re-export all domain model entities, errors, and value objects."""

# Errors
# Provider & Blender DTOs
from .base_provider_vo import (
    AssetDownloadRequestVO,
    AssetDownloadResponseVO,
    AssetMetadataVO,
    AssetSearchRequestVO,
    AssetSearchResponseVO,
    GenerationStartRequestVO,
    GenerationStartResponseVO,
    GenerationStatusRequestVO,
    GenerationStatusResponseVO,
    ImportGeneratedAssetRequestVO,
    ImportGeneratedAssetResponseVO,
    ProviderVO,
)
from .blender_asset_vo import (
    ASSET_TYPE_HDRIS,
    ASSET_TYPE_MODELS,
    ASSET_TYPE_TEXTURES,
    PROVIDER_POLYHAVEN,
    PROVIDER_SKETCHFAB,
    AssetMetadata,
    ImportedAsset,
    create_asset_id,
    create_provider_name,
)

# Command Catalog Data
from .blender_command_vo import (
    CommandCatalog,
    CommandSpec,
)

# Application Configuration
from .blender_config_vo import (
    ApplicationConfigVo,
)
from .blender_job_vo import (
    JOB_STATE_COMPLETED,
    JOB_STATE_FAILED,
    JOB_STATE_PENDING,
    JOB_STATE_RUNNING,
    PROVIDER_HUNYUAN_NAME,
    PROVIDER_HYPER3D_NAME,
    JobStatus,
    create_job_id,
    create_progress,
)
from .blender_mcp_error import (
    AssetNotFoundError,
    BlenderConnectionError,
    BlenderMCPError,
    ConnectionError,
    DomainError,
    ExecutionError,
    InvalidCommandError,
    ProviderError,
    SceneValidationError,
    ValidationError,
)

# Entity models
from .blender_object_entity import (
    ALLOWED_OBJECT_TYPES,
    OBJECT_TYPE_ARMATURE,
    OBJECT_TYPE_CAMERA,
    OBJECT_TYPE_CURVE,
    OBJECT_TYPE_EMPTY,
    OBJECT_TYPE_FONT,
    OBJECT_TYPE_GPENCIL,
    OBJECT_TYPE_LATTICE,
    OBJECT_TYPE_LIGHT,
    OBJECT_TYPE_MESH,
    OBJECT_TYPE_META,
    OBJECT_TYPE_POINTCLOUD,
    OBJECT_TYPE_SURFACE,
    OBJECT_TYPE_VOLUME,
    BlenderObject,
    create_object_id,
)
from .blender_ops_vo import (
    ApplyModifierRequestVO,
    ApplyModifierResponseVO,
    BlenderOpsVO,
    CleanupSceneRequestVO,
    CleanupSceneResponseVO,
    CreatePrimitiveRequestVO,
    CreatePrimitiveResponseVO,
    DeleteObjectRequestVO,
    DeleteObjectResponseVO,
    ExportModelRequestVO,
    ExportModelResponseVO,
    GetObjectInfoRequestVO,
    GetObjectInfoResponseVO,
    GetSceneInfoRequestVO,
    GetSceneInfoResponseVO,
    GetScreenshotRequestVO,
    ImportGlbRequestVO,
    ImportGlbResponseVO,
    PlaceAssetRequestVO,
    PlaceAssetResponseVO,
    RenderRequestVO,
    RenderResponseVO,
    ScreenshotResponseVO,
    SetMaterialRequestVO,
    SetMaterialResponseVO,
    SetObjectTransformRequestVO,
    SetObjectTransformResponseVO,
    SetupEnvironmentRequestVO,
    SetupEnvironmentResponseVO,
)
from .blender_scene_entity import (
    RENDER_ENGINE_CYCLES,
    RENDER_ENGINE_EEVEE,
    SceneAggregate,
    SceneInfo,
)

# Spatial types
from .blender_spatial_vo import (
    BoundingBox,
    Vector3D,
    create_float_triplet,
)

# Branded primitives (NewTypes)
from .core_types_vo import (
    ActionName,
    AssetCount,
    AssetId,
    AssetIdList,
    AssetName,
    AssetType,
    AssetTypeFilter,
    BBoxIntegers,
    BlenderObjectList,
    BlenderVersion,
    CapabilityRef,
    CleanupMode,
    ConfigPath,
    ConfigValue,
    CoordinateList,
    # New VOs added to fix AES006 primitive violations
    CustomerUuid,
    Details,
    DirectoryPath,
    DomainRef,
    DurationMs,
    EnabledFlag,
    ErrorMessage,
    ExitCode,
    ExportFormat,
    FilePath,
    FormatRef,
    HdriId,
    ImageBytes,
    ImageFormat,
    IterationCount,
    JobId,
    JobState,
    LightStrength,
    MaterialName,
    MaxImageSize,
    MaxSize,
    ModifierName,
    NextPageToken,
    ObjectCount,
    ObjectIdList,
    ObjectName,
    ObjectType,
    ParentId,
    PlatformName,
    PortNumber,
    PrimitiveType,
    Progress,
    Prompt,
    ProviderName,
    PythonCode,
    RenderEngine,
    RenderSamples,
    RenderTime,
    ResolutionX,
    ResolutionY,
    ResultLimit,
    ResultUrl,
    RotationVector,
    RuleName,
    SampleCount,
    ScaleFactor,
    ScaleVector,
    SceneId,
    SceneRuleSetName,
    SearchQuery,
    SectionRef,
    ServerName,
    SessionId,
    # Surface-typed primitives
    SkillName,
    StatusString,
    StringList,
    SuccessFlag,
    TagList,
    TaskUuid,
    ThumbnailUrl,
    Timestamp,
    ToolName,
    UseDenoising,
    UserId,
    VersionString,
    WorkflowName,
)

# Telemetry types
from .telemetry_event_entity import (
    EventType,
    TelemetryEvent,
)

__all__ = [
    # Errors
    "BlenderMCPError",
    "DomainError",
    "SceneValidationError",
    "AssetNotFoundError",
    "ValidationError",
    "ConnectionError",
    "ProviderError",
    "ExecutionError",
    "BlenderConnectionError",
    "InvalidCommandError",
    # Branded IDs
    "UserId",
    "SceneId",
    "ObjectName",
    "AssetId",
    "JobId",
    "ProviderName",
    "HdriId",
    "ParentId",
    # Text VOs
    "Prompt",
    "ActionName",
    "RenderEngine",
    "ErrorMessage",
    # Asset/Render/Image/Material VOs
    "AssetType",
    "ImageFormat",
    "PrimitiveType",
    "ExportFormat",
    "MaterialName",
    "ModifierName",
    "RuleName",
    "WorkflowName",
    "SceneRuleSetName",
    # Additional VOs
    "ObjectType",
    "AssetName",
    "JobState",
    "ResultUrl",
    "FilePath",
    "DirectoryPath",
    "CleanupMode",
    "SearchQuery",
    "AssetTypeFilter",
    "ResultLimit",
    "NextPageToken",
    "CoordinateList",
    "ScaleVector",
    "RotationVector",
    "AssetCount",
    "RenderSamples",
    "MaxImageSize",
    "RenderTime",
    "Details",
    "ObjectIdList",
    "BlenderObjectList",
    # Numeric VOs
    "MaxSize",
    "SampleCount",
    "IterationCount",
    "ResolutionX",
    "ResolutionY",
    "PortNumber",
    "ObjectCount",
    "LightStrength",
    # Flags
    "UseDenoising",
    "EnabledFlag",
    "SuccessFlag",
    # Surface-typed primitives
    "SkillName",
    "SectionRef",
    "ServerName",
    "DomainRef",
    "FormatRef",
    "CapabilityRef",
    "ExitCode",
    # Collections
    "AssetIdList",
    "StringList",
    "TagList",
    # New VOs added to fix AES006 primitive violations
    "CustomerUuid",
    "SessionId",
    "Timestamp",
    "VersionString",
    "PlatformName",
    "ToolName",
    "DurationMs",
    "BlenderVersion",
    "StatusString",
    "PythonCode",
    "TaskUuid",
    "ScaleFactor",
    "ImageBytes",
    "BBoxIntegers",
    "ConfigPath",
    "ConfigValue",
    # Entity models
    "BlenderObject",
    "SceneInfo",
    "JobStatus",
    "AssetMetadata",
    "ImportedAsset",
    "SceneAggregate",
    # Object type constants
    "OBJECT_TYPE_MESH",
    "OBJECT_TYPE_CAMERA",
    "OBJECT_TYPE_LIGHT",
    "OBJECT_TYPE_EMPTY",
    "OBJECT_TYPE_ARMATURE",
    "OBJECT_TYPE_CURVE",
    "OBJECT_TYPE_SURFACE",
    "OBJECT_TYPE_META",
    "OBJECT_TYPE_FONT",
    "OBJECT_TYPE_LATTICE",
    "OBJECT_TYPE_GPENCIL",
    "OBJECT_TYPE_VOLUME",
    "OBJECT_TYPE_POINTCLOUD",
    "ALLOWED_OBJECT_TYPES",
    # Render engine constants
    "RENDER_ENGINE_CYCLES",
    "RENDER_ENGINE_EEVEE",
    # Asset/Provider constants
    "ASSET_TYPE_HDRIS",
    "ASSET_TYPE_TEXTURES",
    "ASSET_TYPE_MODELS",
    "PROVIDER_POLYHAVEN",
    "PROVIDER_SKETCHFAB",
    "PROVIDER_HYPER3D_NAME",
    "PROVIDER_HUNYUAN_NAME",
    # Job state constants
    "JOB_STATE_PENDING",
    "JOB_STATE_RUNNING",
    "JOB_STATE_COMPLETED",
    "JOB_STATE_FAILED",
    # Progress
    "Progress",
    "ThumbnailUrl",
    # Factories
    "create_asset_id",
    "create_job_id",
    "create_provider_name",
    "create_object_id",
    "create_progress",
    "create_float_triplet",
    # Rich value objects
    "Vector3D",
    "BoundingBox",
    # Telemetry
    "EventType",
    "TelemetryEvent",
    # Command Catalog Data
    "CommandCatalog",
    "CommandSpec",
    # Application Configuration
    "ApplicationConfigVo",
    # Provider & Blender DTOs
    "ProviderVO",
    "BlenderOpsVO",
    "AssetSearchRequestVO",
    "AssetMetadataVO",
    "AssetSearchResponseVO",
    "AssetDownloadRequestVO",
    "AssetDownloadResponseVO",
    "GenerationStartRequestVO",
    "GenerationStartResponseVO",
    "GenerationStatusRequestVO",
    "GenerationStatusResponseVO",
    "ImportGeneratedAssetRequestVO",
    "ImportGeneratedAssetResponseVO",
    "CleanupSceneRequestVO",
    "CleanupSceneResponseVO",
    "SetupEnvironmentRequestVO",
    "SetupEnvironmentResponseVO",
    "GetSceneInfoRequestVO",
    "GetSceneInfoResponseVO",
    "PlaceAssetRequestVO",
    "PlaceAssetResponseVO",
    "GetObjectInfoRequestVO",
    "GetObjectInfoResponseVO",
    "SetObjectTransformRequestVO",
    "SetObjectTransformResponseVO",
    "DeleteObjectRequestVO",
    "DeleteObjectResponseVO",
    "CreatePrimitiveRequestVO",
    "CreatePrimitiveResponseVO",
    "SetMaterialRequestVO",
    "SetMaterialResponseVO",
    "ApplyModifierRequestVO",
    "ApplyModifierResponseVO",
    "RenderRequestVO",
    "RenderResponseVO",
    "GetScreenshotRequestVO",
    "ScreenshotResponseVO",
    "ImportGlbRequestVO",
    "ImportGlbResponseVO",
    "ExportModelRequestVO",
    "ExportModelResponseVO",
]
