import { describe, it, expect, vi, beforeEach } from 'vitest';
import { AgentOrchestrator } from '../../src/agent/request_flow_facade';
import {
  createEmailAddress, asPassword, asUserAgent, asClientIp,
  asAuthToken, asTimestamp, asName, asUserId
} from '../../src/taxonomy';
import { createTestContainer } from './test_utils';

/**
 * E2E: Auth Lifecycle
 * 
 * Responsibility:
 * Verifies the orchestration of authentication and session management.
 * Covers user registration, multi-session login, access code verification,
 * and secure session termination.
 */
describe('e2e: Auth Lifecycle Management', () => {
  let mockDb: any;
  let mockCrypto: any;
  let mockSessionAuth: any;
  let orchestrator: AgentOrchestrator;

  beforeEach(() => {
    const container = createTestContainer();
    mockDb = container.database;
    mockCrypto = container.crypto;
    mockSessionAuth = container.session;
    orchestrator = new AgentOrchestrator(container);
  });

  describe('Primary Login Flow', () => {
    it('executes a full login/validate/logout cycle', async () => {
      const email = createEmailAddress('auth_tester@domain.com');
      const password = asPassword('ComplexPass123!');
      const meta = { userAgent: asUserAgent('Mozilla/5.0'), clientIp: asClientIp('192.168.1.1') };

      // Setup Mocks for success path
      mockDb.getUserByEmail.mockResolvedValue({
        id: 'u_tester',
        email,
        passwordHash: 'hashed_pw',
        displayName: 'Auth Tester',
        createdAt: asTimestamp(new Date().toISOString()),
        isDeleted: false
      });
      mockCrypto.verifyPassword.mockResolvedValue(true);
      mockSessionAuth.createSession.mockResolvedValue({ token: 'secure_session_token', session: { id: 's_active' as any } });
      mockSessionAuth.validateSession.mockResolvedValue({
        userId: 'u_tester',
        sessionId: 's_active',
        expiresAt: asTimestamp(new Date().toISOString())
      });

      // 1. Login
      const loginResult = await orchestrator.login(email, password, meta);
      expect(loginResult.token).toBe('secure_session_token');
      expect(mockCrypto.verifyPassword).toHaveBeenCalledWith(password, 'hashed_pw');

      // 2. Validate
      const validateResult = await orchestrator.validateSession(asAuthToken('secure_session_token'));
      expect(validateResult).not.toBeNull();
      expect(validateResult!.userId).toBe('u_tester');

      // 3. Logout
      await orchestrator.logout(asAuthToken('secure_session_token'));
      expect(mockSessionAuth.destroySession).toHaveBeenCalledWith('secure_session_token');
    });

    it('rejects login with invalid credentials', async () => {
      const email = createEmailAddress('wrong@domain.com');
      const password = asPassword('bad_pass');

      mockDb.getUserByEmail.mockResolvedValue({ passwordHash: 'real_hash' });
      mockCrypto.verifyPassword.mockResolvedValue(false);

      await expect(orchestrator.login(email, password, { userAgent: asUserAgent('test'), clientIp: asClientIp('0.0.0.0') }))
        .rejects.toThrow();
    });

    it('handles non-existent users gracefully during login', async () => {
      mockDb.getUserByEmail.mockResolvedValue(null);

      await expect(orchestrator.login(createEmailAddress('none@none.com'), asPassword('p'), { userAgent: asUserAgent('t'), clientIp: asClientIp('c') }))
        .rejects.toThrow();
    });
  });


  describe('User Account Lifecycle Operations', () => {
    it('creates a new user and registers secret material', async () => {
      const name = asName('Newbie');
      mockDb.createUser.mockResolvedValue({ id: 'u_new' });
      mockCrypto.generateSecurePassword.mockReturnValue('AutoGenerated123');

      const result = await orchestrator.createUser(name);

      expect(result.user.id).toBe('u_new');
      expect(result.credentials.password).toBe('AutoGenerated123');
      expect(mockDb.createUser).toHaveBeenCalledWith(expect.objectContaining({ displayName: 'newbie' }));
    });

    it('performs a password update and ensures hash matches', async () => {
      const userId = asUserId('u_update');
      const newPassword = asPassword('NewSecret123!');

      mockDb.updateUser.mockResolvedValue(true);
      mockDb.updateUserPassword.mockResolvedValue(true);
      mockDb.getUserById.mockResolvedValue({ id: userId, name: 'New Name' });

      await orchestrator.updateUser(userId, { password: newPassword });

      expect(mockDb.updateUserPassword).toHaveBeenCalledWith(userId, expect.any(String));
      // No other fields, so updateUser is not called
      expect(mockDb.updateUser).not.toHaveBeenCalled();
    });

    it('executes soft and hard deletes with session invalidation simulation', async () => {
      const userId = asUserId('u_gone');

      mockDb.softDeleteUser.mockResolvedValue(true);
      await orchestrator.softDeleteUser(userId);
      expect(mockDb.softDeleteUser).toHaveBeenCalledWith(userId);

      mockDb.deleteUser.mockResolvedValue(true);
      await orchestrator.deleteUser(userId);
      expect(mockDb.deleteUser).toHaveBeenCalledWith(userId);
    });
  });

  describe('Identity Verification & State', () => {
    it('performs a health check on the auth system', async () => {
      const health = await orchestrator.healthCheck();
      expect(health.status).toBe('healthy');
    });

    it('lists all users for administrative purposes', async () => {
      mockDb.getUsers.mockResolvedValue([
        { id: 'u1', displayName: 'One' },
        { id: 'u2', displayName: 'Two' }
      ]);

      const users = await orchestrator.listUsers();
      expect(users).toHaveLength(2);
      expect(users[0]!.displayName).toBe('One');
    });
  });
});
